apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-db-init-configmap
data:
  init.sql: |
      CREATE DATABASE IF NOT EXISTS snippetbox CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
  
      CREATE USER IF NOT EXISTS 'web'@'%';
      GRANT SELECT, INSERT, UPDATE, DELETE ON snippetbox.* TO 'web'@'%';
      ALTER USER 'web'@'%' IDENTIFIED BY 'pass';